### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ungeeked**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@ungeeked no u

**Comment by ungeeked** [comment]
@akhilnarang y u do this @akhilnarang  ;_:

**Comment by akhilnarang** [comment]
@ungeeked pugloif @ungeeked, pugloif

**Comment by ungeeked** [comment]
@akhilnarang kek

**Comment by akhilnarang** [comment]
@ungeeked kek yourself

**Pull request merged**
